services:
  mariadb:
    image: mariadb:5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test

  cassandra:
      image: cassandra:latest

  elasticsearch:
      image: elasticsearch:7.17.10
      environment:
          - discovery.type=single-node

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2

  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_BROKER_ID: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  mongo:
    image: mongo:latest

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test

  neo4j:
    image: neo4j:latest
    environment:
      NEO4J_AUTH: neo4j/asd456HJg

  oracle:
    environment:
      - ORACLE_PASSWORD=Test1234
    image: gvenzl/oracle-free:latest

  postgres:
    hostname: postgres.clugest.home
    image: postgres:latest
    environment:
      POSTGRES_USER: clugestuser
      POSTGRES_PASSWORD: kjl3J9h9hH32Gddhk
      POSTGRES_DB: clugest

  redis:
    image: redis:latest

  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      SA_PASSWORD: Test1234
      ACCEPT_EULA: Y
      MSSQL_PID: Developer