services:
  sqlserver:
    hostname: sqlserver.clugest.home
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      SA_PASSWORD: kjl3J9h9hH32Gddhk
      ACCEPT_EULA: Y
      MSSQL_PID: Developer

  oracle:
    hostname: oracle.clugest.home
    environment:
      - ORACLE_PASSWORD=kjl3J9h9hH32Gddhk
    image: gvenzl/oracle-free:latest

  postgres:
    hostname: postgres.clugest.home
    image: postgres:latest
    environment:
      POSTGRES_USER: clugestuser
      POSTGRES_PASSWORD: kjl3J9h9hH32Gddhk
      POSTGRES_DB: clugest

  mariadb:
    hostname: mariadb.clugest.home
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: kjl3J9h9hH32Gddhk
      MYSQL_DATABASE: clugest
      MYSQL_USER: clugestuser
      MYSQL_PASSWORD: kjl3J9h9hH32Gddhk

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: kjl3J9h9hH32Gddhk
      MYSQL_DATABASE: clugest
      MYSQL_USER: clugestuser
      MYSQL_PASSWORD: kjl3J9h9hH32Gddhk

  cassandra:
    hostname: cassandra.clugest.home
    image: bitnami/cassandra:latest
    environment:
      CASSANDRA_CLUSTER_NAME: clugest_cluster
      CASSANDRA_USER: clugest
      CASSANDRA_PASSWORD_SEEDER: yes
      CASSANDRA_PASSWORD: kjl3J9h9hH32Gddhk
  #        CASSANDRA_DATACENTER: dc1

  elasticsearch:
    hostname: elasticsearch.clugest.home
    image: elasticsearch:7.17.10
    environment:
      - discovery.type=single-node

  zookeeper:
    hostname: zookeeper.clugest.home
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2

  kafka:
    hostname: kafka.clugest.home
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_BROKER_ID: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  mongo:
    hostname: mongo.clugest.home
    environment:
      - MONGO_INITDB_DATABASE=clugest
      - MONGO_INITDB_ROOT_USERNAME=clugestuser
      - MONGO_INITDB_ROOT_PASSWORD=kjl3J9h9hH32Gddhk
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./docker/mongo/:/data/db

  neo4j:
    hostname: neo4j.clugest.home
    image: neo4j:latest
    environment:
      NEO4J_AUTH: neo4j/kjl3J9h9hH32Gddhk

  redis:
    hostname: redis.clugest.home
    image: redis:latest
